version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
        bash ./dev/build
        docker run dtn-client:local npm test