version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
          docker build -f ./docker/Dockerfile -t dtn-client:local .
          docker run dtn-client:local npm test